#define DYNEventSpecial
#define DYNCallStackData
/* DSblock model generated by Dymola from Modelica model TestCase
 Dymola Version 2024x, 2023-10-06 translated this at Wed Dec  4 14:49:25 2024

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    1
#define NY_    1
#define NW_    1
#define NWP_   0
#define NP_    2
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1129037508
#define NHash2_ 1915068977
#define NHash3_ -1428718569
#define NI_    0
#define NRelF_ 1
#define NRel_  1
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    3
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 2
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="TestCase";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
#if defined(_WIN32)
"C:/Users/Henn/AppData/Roaming/DassaultSystemes/Dymola/dymola.lic"
#else
"/mnt/c/Users/Henn/AppData/Roaming/DassaultSystemes/Dymola/dymola.lic"
#endif
;
DYMOLA_STATIC const char*GUIDString="{8adca5ab-259b-41a5-ad2b-995f269f0ae1}";
DYMOLA_STATIC const double cvodeTolerance=1E-05;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,0) = DYNdelay(DYNX(U_,0), DYNX(DP_,1), DYNX(DP_,1), 0, "delay(fixedDelay.u, fixedDelay.delayTime)");
DYNX(Y_,0) = GreaterEqual(DYNX(W_,0),"greaterEqualThreshold.u", DYNX(DP_,0),
  "greaterEqualThreshold.threshold", 0);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

/* Introducing 0 common subexpressions and reusing 1 variables totally whereof 1
   are global used in 0 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(W_,0) = DYNdelay(DYNX(U_,0), DYNX(DP_,1), DYNX(DP_,1), 1, "delay(fixedDelay.u, fixedDelay.delayTime)");
DYNX(Y_,0) = GreaterEqual(DYNX(W_,0),"greaterEqualThreshold.u", DYNX(DP_,0),
  "greaterEqualThreshold.threshold", 0);

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("greaterEqualThreshold.threshold", "Comparison with respect to threshold",\
 0, 0.01, 0.0,0.0,0.0,0,560)
DeclareVariable("greaterEqualThreshold.u", "Connector of Real input signal", 0, \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("greaterEqualThreshold.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "y1", 1, 3, 0, 65)
DeclareOutput("y1", "Connector of Boolean output signal [:#(type=Boolean)]", 0, \
false, 0.0,0.0,0.0,0,642)
DeclareAlias2("fixedDelay.u", "Connector of Real input signal", "u1", 1, 2, 0, 0)
DeclareAlias2("fixedDelay.y", "Connector of Real output signal", \
"greaterEqualThreshold.u", 1, 5, 0, 0)
DeclareParameter("fixedDelay.delayTime", "Delay time of output with respect to input signal [s]",\
 1, 1, 0.0,0.0,0.0,0,560)
DeclareInput("u1", "Connector of Real input signal [:#(prefix=input)]", 0, 0.0, \
0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
